# Generated by Django 4.1.5 on 2023-01-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='year',
            field=models.IntegerField(default=''),
        ),
    ]
