# Generated by Django 4.1.5 on 2023-01-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0002_alter_movies_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='img',
            field=models.ImageField(default='imagess', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
